before:
  hooks:
    - go mod tidy -v
builds:
  - id: openai
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm
      - 386
      - arm64
      - amd64
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: 386
    main: ./
    binary: openai
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{.ProjectName}}"
archives:
  - name_template: "openai_{{ .Os }}_{{ .Arch }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
